helpdesk/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include
from django.conf import settings
from django.conf.urls.static import static

from helpdesk.views import index
urlpatterns = [

    path('admin/', admin.site.urls),

    #path('<int:id>/', views.update_data, name="updatedata"),
    path('', index, name='index'),
    path('menu/', include('menu.urls')),
    path('', include('login.urls')),
    path('input/', include('input.urls')),   
    path('menu/', include('keluhan.urls')),  
    path('menu/', include('view_keluhan.urls')),   
    path('dashboard/', include('dashboard.urls')),
]

urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

keluhan/urls.py
from django.urls import path
from . import views

urlpatterns = [
	path('keluhan', views.keluhan_teknisi, name="problem"),
  path('keluhanmu', views.keluhan_pengguna, name="keluhanmu"),
  path('search_teknisi', views.search_teknisi, name="search_teknisi"),
  path('tambahkan-keluhan', views.tambahkan_keluhan, name="tambahkan-problem"),
  path('keluhan/<int:id>', views.update_keluhan, name="update-keluhan"),
    
]

menu/urls.py
from django.urls import path
from . import views

urlpatterns = [
	path('list-user', views.list_user, name='list_user'),
    path('help', views.help, name='help'),    
]

keluhan/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
# Create your models here.
status = (
	(1,'Diajukan'),
	(2,'Diproses'),
    (3,'Selesai'),
)

judul = (
	(1,'Permasalahan website'),
	(2,'Permasalahan database'),
    (3,'Permasalahan lainnya'),
)

class List_keluhan(models.Model):
    user = models.ForeignKey(User, on_delete= models.CASCADE,related_name='problem' , blank = True , null = True )
    judul = models.IntegerField(choices = judul)
    pembahasan = models.CharField(max_length=5000)
    teknisi = models.ForeignKey(User, on_delete=models.SET_NULL, related_name='teknisi', blank=True, null=True)
    status = models.IntegerField(choices = status ,default=1)
    date_posted = models.DateTimeField(default=timezone.now)
    

keluhan/forms.py
from dataclasses import fields
from pyexpat import model
from tkinter.tix import Select
from django.core import validators
from django import forms
from .models import List_keluhan

class KeluhanForms(forms.ModelForm):
     class Meta:
        model = List_keluhan
        fields = ['judul' , 'pembahasan' ]
        widgets = {
            'judul': forms.Select(attrs={'class':'form-control'}),
            'pembahasan': forms.Textarea(attrs={'class':'form-control'}),
            
        }

class TeknisiKeluhan(forms.ModelForm):
     class Meta:
        model = List_keluhan
        fields = ['teknisi' , 'status' ]
        widgets = { 
            'teknisi': forms.Select(attrs={'class':'form-control'}),
            'status': forms.Select(attrs={'class':'form-control'}),
            
        }

keluhan/views.py
from django.shortcuts import render, redirect, HttpResponseRedirect
from input.models import Keluhan
from .forms import KeluhanForms, TeknisiKeluhan
from .models import List_keluhan 
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
# Create your views here.
TEMPLATE_DIRS = (
    'os.path.join(BASE_DIR, "templates"),'
)

# function untuk menambahkan

@login_required
def keluhan_teknisi(request):
  if request.method == 'POST':
   fm = KeluhanForms(request.POST)
   if fm.is_valid(): 
     jd = fm.cleaned_data['judul']
     pb = fm.cleaned_data['pembahasan']
     reg = List_keluhan(judul=jd, pembahasan=pb).save()
     reg.save()
     fm = KeluhanForms()
  else:
   fm = KeluhanForms()
   prob = List_keluhan.objects.all().order_by('-date_posted')
   p = Paginator(prob, 3) 
   page_number = request.GET.get('page')
   try:
        teknisi = p.get_page(page_number)  # returns the desired page object
   except PageNotAnInteger:
        # if page_number is not an integer then assign the first page
        teknisi = p.page(1)
   except EmptyPage:
        # if page is empty then return last page
        teknisi = p.page(p.num_pages)
    # sending the page object to index.html
  
   context = { 
        'teknisi': teknisi
        }
   return render(request, 'keluhan.html',context)

@login_required
def keluhan_pengguna(request):
  if request.method == 'POST':
   fm = KeluhanForms(request.POST)
   if fm.is_valid(): 
     jd = fm.cleaned_data['judul']
     pb = fm.cleaned_data['pembahasan']
     reg = List_keluhan(judul=jd, pembahasan=pb).save()
     reg.save()
     fm = KeluhanForms()
  else:
   fm = KeluhanForms()
   prob = List_keluhan.objects.filter(user=request.user)
   p = Paginator(prob, 3) 
   page_number = request.GET.get('page')
   try:
        pengguna = p.get_page(page_number)  # returns the desired page object
   except PageNotAnInteger:
        # if page_number is not an integer then assign the first page
        pengguna = p.page(1)
   except EmptyPage:
        # if page is empty then return last page
        pengguna = p.page(p.num_pages)
    # sending the page object to index.html
  
   context = { 
        'pengguna': pengguna
        }
   return render(request, 'keluhanmu.html',context)

@login_required
def tambahkan_keluhan(request):
  if request.method == 'POST':
   problem_forms = KeluhanForms(request.POST)
   if problem_forms.is_valid(): 
     post = problem_forms.save(commit=False)
     post.user = request.user
     post.save()
     return redirect('tambah_gambar')
  else:
   problem_forms = KeluhanForms()
   prob = List_keluhan.objects.all()
  return render(request, 'tambahkan_keluhan.html', {'form':problem_forms})

@login_required
def update_keluhan(request, id):
  if request.method == 'POST':
    pi = List_keluhan.objects.get(pk=id)
    fm = TeknisiKeluhan(request.POST, instance=pi)
    if fm.is_valid():
      fm.save()
      return redirect('problem')
  else:
    pi = List_keluhan.objects.get(pk=id)
    fm = TeknisiKeluhan(instance=pi)
  return render(request, 'update_keluhan.html', {'form':fm})

@login_required
def search_teknisi(request):
    if request.method == "POST":
        pencarian = request.POST['pencarian']
        hasil = List_keluhan.objects.filter(teknisi__username__contains=pencarian)
              
        return render(request, "search_keluhan.html",
        {'pencarian':pencarian,'hasil':hasil})
    else:
        return render(request, "search_keluhan.html",
        {})

keluhan/templates/keluhan.html
{% extends 'base.html' %} {% load auth_extras %} {% load wrap_filter%} {% block css %} {% load static %}
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.11.5/css/jquery.dataTables.min.css" />
{% endblock css %} {% block content %} {% load auth_extras%}
<link rel="shortcut icon" href="{% static 'foto/keluhan.ico'%}" />
<h3 style="-webkit-text-fill-color: transparent; -webkit-text-stroke: 1px black;">Keluhan</h3>
<a href="{% url 'keluhanmu' %}" class="btn btn-outline-primary"> tampilkan keluhan saya </a>
<form class="form-inline my-2 my-lg-0 justify-content-end" method="POST" action="{% url 'search_teknisi' %}" >
  {% csrf_token %}
  <input class="form-control mr-sm-2 col-sm-2" type="search"placeholder="cari teknisi dari keluhan...." aria-label="Search" name="pencarian">
  <button class="btn btn-outline-primary my-2 my-sm-0" type="submit">go</button>
</form><br>
<div class="tombol">
  <a href="{% url 'tambahkan-problem' %}" class="btn btn-outline-primary">Tambahkan</a>
</div>  
<div class="bungkus">
  <div class="menu">

  </div>
  <br />
  <table class="table" id="myTable">
    <thead>
      <tr>
        <th scope="col">User</th>
        <th scope="col">Judul</th>
        <th scope="col">Pembahasan</th>
        <th scope="col">Teknisi</th>
        <th scope="col">Status</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      {% for st in teknisi.object_list %}
      <tr>
        <td>{{st.user}}</td>
        <td>{{st.get_judul_display}}</td>
        <td>{{st.pembahasan|text_wrap}}</td>
        <td>{{st.teknisi}}</td>
        <td>{{st.get_status_display}}</td>
        {% if request.user|has_group:"Teknisi" %}
        <td>
          <a href="{% url 'update-keluhan' st.id %}" class="btn btn-outline-warning"> Update </a>
      </tr>
      {% endif %}
      {% endfor %}
    </tbody>
  </table>

  <!--pagination-->
  <center>
    <div style="justify-content:left;"
    {%if teknisi.has_previous %} 
    <ul class="pagination">
      <li class="page-item">
        <a class="page-link" href="?page={{teknisi.previous_page_number}}">Sebelumnya </a> {# link to the prev page #}
    </li> </ul> </div>
        {% endif %} 
        <span>ini adalah halaman ke {{teknisi.number}} </span>
<div style="justify-content: end;"
    {%if teknisi.has_next %} {# whether the next page exists #}
    <ul class="pagination">
      <li class="page-item">
        <a class="page-link" href="?page={{teknisi.next_page_number}}">Selanjutnya </a> {# link to the next page #}
    {% endif %}
      </div>
</center>
<!--end pagination-->
  {% endblock content %} {% block js %}
  <script href="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js"></script>
  <script>
    $(document).ready(function () {
      $("#myTable").DataTable();
    });
  </script>
  {% endblock js %}
</div>

keluhan/templates/keluhanmu.html
{% extends 'base.html' %} {% load auth_extras %} {% load wrap_filter%} {% block css %} {% load static %}
<link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.11.5/css/jquery.dataTables.min.css" />
{% endblock css %} {% block content %} {% load auth_extras%}
<link rel="shortcut icon" href="{% static 'foto/keluhan.ico'%}" />
<h3 style="-webkit-text-fill-color: transparent; -webkit-text-stroke: 1px black;">Informasi dari keluhan saya</h3>
<div class="tombol">
  <a href="{% url 'tambahkan-problem' %}" class="btn btn-outline-primary">Tambahkan</a>
</div>  
<div class="bungkus">
  <div class="menu" style="background-color: aquamarine">

  </div>
  <br />
  <table class="table" id="myTable">
    <thead>
      <tr>
        <th scope="col">User</th>
        <th scope="col">Judul</th>
        <th scope="col">Pembahasan</th>
        <th scope="col">Teknisi</th>
        <th scope="col">Status</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      {% for st in pengguna.object_list %}
      <tr>
        <td>{{st.user}}</td>
        <td>{{st.get_judul_display}}</td>
        <td>{{st.pembahasan|text_wrap}}</td>
        <td>{{st.teknisi}}</td>
        <td>{{st.get_status_display}}</td>
        {% if request.user|has_group:"Teknisi" %}
        <td>
          <a href="{% url 'update-keluhan' st.id %}" class="btn btn-outline-warning"> Update </a>
      </tr>
      {% endif %}
      {% endfor %}
    </tbody>
  </table>

  <!--pagination-->
  <center>
    <div style="justify-content:left;"
    {%if pengguna.has_previous %} 
    <ul class="pagination">
      <li class="page-item">
        <a class="page-link" href="?page={{pengguna.previous_page_number}}">Sebelumnya </a> {# link to the prev page #}
    </li> </ul> </div>
        {% endif %} 

<div style="justify-content: end;"
    {%if pengguna.has_next %} 
    <ul class="pagination">
      <li class="page-item">
        <a class="page-link" href="?page={{pengguna.next_page_number}}">Selanjutnya </a> {# link to the next page #}
    {% endif %}
      </div>
</center>
<!--end pagination-->
  {% endblock content %} {% block js %}
  <script href="https://cdn.datatables.net/1.11.5/js/jquery.dataTables.min.js"></script>
  <script>
    $(document).ready(function () {
      $("#myTable").DataTable();
    });
  </script>
  {% endblock js %}
</div>

keluhan/templates/search_keluhan.html
{% extends 'base.html' %} {% load static %} {% load auth_extras %}{% load wrap_filter%}
{% block content %}
 <center>
       <h3> beberapa kata kunci terkait : {{ pencarian }} </h3>
      <br>
      <form class="form-inline my-2 my-lg-0 justify-content-end" method="POST" action="{% url 'search_teknisi' %}" >
        {% csrf_token %}
        <input class="form-control mr-sm-2 col-sm-2" type="search"placeholder="cari teknisi dari keluhan...." aria-label="Search" name="pencarian">
        <button class="btn btn-outline-primary my-2 my-sm-0" type="submit">go</button>
      </form><br>
<div class="row">
  <div class="col-12">
    <table class="table" id="myTable">
      <thead>
        <tr>
          <th scope="col">User</th>
          <th scope="col">Judul</th>
          <th scope="col">Pembahasan</th>
          <th scope="col">Teknisi</th>
          <th scope="col">Status</th>
          <th></th>
        </tr>
      </thead>
      <tbody>
        {% for hasil in hasil %}
        <tr>
          <td>{{hasil.user}}</td>
          <td>{{hasil.get_judul_display}}</td>
          <td>{{hasil.pembahasan|text_wrap}}</td>
          <td>{{hasil.teknisi}}</td>
          <td>{{hasil.get_status_display}}</td>
        {% endfor %}
      </tbody>
    </table>
    <!--pagination-->
    <center>
      <div style="justify-content:left;"
      {% if teknisi.has_previous %} 
      <ul class="pagination">
        <li class="page-item">
          <a class="page-link" href="?page={{teknisi.previous_page_number}}">Sebelumnya </a> {# link to the prev page #}
      </li> </ul> </div>
          {% endif %} 
  
  <div style="justify-content: end;"
      {%if teknisi.has_next %}
      <ul class="pagination">
        <li class="page-item">
          <a class="page-link" href="?page={{teknisi.next_page_number}}">Selanjutnya </a> {# link to the next page #}
      {% endif %}
        </div>
  </center>
  <!--end pagination-->
    {% endblock content %} 

keluhan/templates/tambahkan_keluhan.html
{% extends 'base.html' %} {% block content %} {% load static %}
<link rel="shortcut icon" href="{% static 'foto/keluhan.ico'%}" />
<div class="col-sm-4">
    
    <h4 class="text-center alert alert-info">Menambahkan Keluhan</h4>
    <form action="" method="POST">

     {% csrf_token %}
     {{form.as_p}}

    <input type="Submit" class="btn btn-succes" id="berhasil2" onclick="berhasil1()" value="Tambah">
    </from>
</div>
<script>
    function berhasil1() {
        var a =
    document.getElementById("berhasil2");
            alert("data berhasil ditambahkan");
    }
</script>
{% endblock content%}

keluhan/templates/update_keluhan.html
{% extends 'base.html' %} {% block content %}
{% load static %}
<link rel="shortcut icon" href="{% static 'foto/keluhan.ico'%}" />
<div class="row">
  <div class="col-sm-8 offset-2">
    <h4 class="alert alert-info">Update Keluhan</h4>
    <form action="" method="post">
      {% csrf_token %} {{form.as_p}}
 </button><input type="submit" class="btn btn-succes" value="Update" />
 
    </form>
  </div>
</div>
{% endblock content %}